DROP DATABASE IF EXISTS delphi_ajx;

CREATE DATABASE delphi_ajx
  DEFAULT CHARACTER SET utf8mb4
  DEFAULT COLLATE utf8mb4_general_ci;

USE delphi_ajx;

CREATE TABLE TB_CLIENTES (
    CODIGO     INT NOT NULL AUTO_INCREMENT,
    NOME       VARCHAR(50)  NOT NULL,
    TELEFONE   VARCHAR(15)  NOT NULL,
    DNASC      DATE         NOT NULL,
    SEXO       CHAR(1)      NOT NULL COMMENT 'M ou F',
    CPF        CHAR(11)     NOT NULL,
    CIDADE     VARCHAR(60)  NOT NULL,
    ESTADO     CHAR(2)      NOT NULL,
    ENDERECO   VARCHAR(100) NOT NULL,
    BAIRRO     VARCHAR(100) NOT NULL,
    ATIVO      TINYINT(1)   NOT NULL DEFAULT 1 COMMENT '0 = Não, 1 = Sim',

    CONSTRAINT PK_TB_CLIENTES PRIMARY KEY (CODIGO),
    CONSTRAINT UQ_TB_CLIENTES_CPF UNIQUE (CPF)
) ENGINE=InnoDB;

CREATE TABLE TB_SERVICOS (
    CODIGO          INT NOT NULL AUTO_INCREMENT,
    NOME            VARCHAR(30)  NOT NULL,
    DESCRICAO       VARCHAR(100),
    DATA_CADASTRO   DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT PK_TB_SERVICOS PRIMARY KEY (CODIGO)
) ENGINE=InnoDB;

CREATE TABLE TB_CARDCLIENTE (
    CODIGO     INT NOT NULL AUTO_INCREMENT,
    CLIENTE    INT NOT NULL,
    VALOR      DECIMAL(10,2) NOT NULL COMMENT 'Saldo atual',
    ATIVO      TINYINT(1) NOT NULL DEFAULT 1 COMMENT '0 = Inativo, 1 = Ativo',

    CONSTRAINT PK_TB_CARDCLIENTE PRIMARY KEY (CODIGO),
    CONSTRAINT FK_CARDCLIENTE_CLIENTE
        FOREIGN KEY (CLIENTE)
        REFERENCES TB_CLIENTES (CODIGO)
        ON DELETE RESTRICT
        ON UPDATE CASCADE
) ENGINE=InnoDB;

CREATE INDEX IDX_CARDCLIENTE_CLIENTE
    ON TB_CARDCLIENTE (CLIENTE);

CREATE TABLE TB_MOVIMENTACOESCLIENTE (
    CODIGO        INT NOT NULL AUTO_INCREMENT,
    CARDCLIENTE   INT NOT NULL,
    SERVICO       INT NOT NULL,
    TIPO          TINYINT(1) NOT NULL COMMENT '0 = Saída | 1 = Entrada',
    VALOR         DECIMAL(10,2) NOT NULL COMMENT 'Nunca zero',
    DATA          DATE NOT NULL,

    CONSTRAINT PK_TB_MOVIMENTACOESCLIENTE PRIMARY KEY (CODIGO),

    CONSTRAINT FK_MOV_CARDCLIENTE
        FOREIGN KEY (CARDCLIENTE)
        REFERENCES TB_CARDCLIENTE (CODIGO)
        ON DELETE CASCADE
        ON UPDATE CASCADE,

    CONSTRAINT FK_MOV_SERVICO
        FOREIGN KEY (SERVICO)
        REFERENCES TB_SERVICOS (CODIGO)
        ON DELETE RESTRICT
        ON UPDATE CASCADE,

    CONSTRAINT CK_MOV_VALOR CHECK (VALOR <> 0)
) ENGINE=InnoDB;
